apiVersion: v1
kind: Service
metadata:
  name: orderservice-poc-service
  labels:
    app: mini-web-shop-poc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: orderservice-poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-poc-deployment
  labels:
    app: mini-web-shop-poc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mini-web-shop-poc
  template:
    metadata:
      labels:
        app: mini-web-shop-poc
    spec:
      containers:
      - name: orderservice
        image: hitzspb/orderservice:latest
        resources:
          requests:
            memory: "300Mi"
            cpu: "150m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        ports:
           - containerPort: 443