apiVersion: v1
kind: Namespace
metadata:
  name: orderservice-poc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: orderservice-poc
  name: "seq-provisioner"
parameters:
  blocksize: "33554432"
  container: seqclusterstorage
  dynamic: "true"
  group: clustergroup-unikdevcluster # same as the default storageclass
  hostname: AKSTESTHOST.uniktest.local # same as the default storageclass
  logicalsectorsize: "4096"
  physicalsectorsize: "4096"
  port: "55000"
  fsType: ext4 # refer to the note above to determine when to include this parameter
provisioner: disk.csi.akshci.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: orderservice-poc
  name: seq-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: seq-provisioner
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Secret
metadata:
  namespace: orderservice-poc
  name: mssql-env
stringData:
  MSSQL_SA_PASSWORD: "ThisIsMyTopSecretPa$$Wrod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: orderservice-poc
spec:
  replicas: 1
  selector:
     matchLabels:
       app: seq
  template:
    metadata:
      labels:
        app: seq
  spec:
    replicas: 1
    containers:
    - name: seq
      image: datalust/seq:latest
      ports:
      - containerPort: 80
      - containerPort: 5341
      env:
      - name: ACCEPT_EULA
        value: "Y"
      volumeMounts:
      - name: volume
        mountPath: "/data"
    volumes:
      - name: seq-storage
        persistentVolumeClaim:
          claimName: seq-data
---
apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: orderservice-poc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: seq    