apiVersion: v1
kind: Namespace
metadata:
  name: orderservice-poc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: orderservice-poc
  name: "orderpoc-provisioner"
provisioner: "kubernetes.io/no-provisioner"
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - mfsymlinks
  - cache=strict
  - actimeo=30
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
  namespace: orderservice-poc
spec:
  storageClassName: orderpoc-provisioner
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/aks-hci"           
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: orderservice-poc
  name: mssql-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: orderpoc-provisioner
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  namespace: orderservice-poc
  name: mssql-env
stringData:
  MSSQL_SA_PASSWORD: "ThisIsMyTopSecretPa$$Wrod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orderservice-poc
  name: mssql-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumeMounts:
          - name: mssql-storage
            mountPath: /var/opt/mssql 
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-env
              key: MSSQL_SA_PASSWORD
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  namespace: orderservice-poc
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer