version: '3.4'

services:
  SqlServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
  unik.webshop.customerservice.api:
    image: ${DOCKER_REGISTRY-}Unikwebshopcustomerserviceapi
    build:
      context: .
      dockerfile: Unik.WebShop.CustomerService.Api/Dockerfile
    environment:
      Server: SqlServer
      Port: 1433
      db: customerservice
      User: sa
      Password: "Your_password123"
    ports: 
      - "8051:80"
    depends_on:
      - SqlServer  